### ISSUE TITLE
todo for fm 

### ISSUE THREAD

**Issue by lyhlbyl** [ggrov/tacny#24]
A TODO list for the FM paper with high prioroty
- [x] `post_conds() / post_conds(c : Element)`
  to get the post condition of the current method  or a method call (?? how to reference such a call)
- [x] `pre_conds() / pre_cond(c : Element)`
  similar to post_cond.
- [x]  rename: `extract_guard` -> `loop_guard`
- [x] `fresh_lem_name(name : string) : string`
  to generate a name for a lemma, if the given string is fresh, return as it is, otherwise generate fresh 
- [x] Macro-expansion:  exmaples in ../tacny-theory/papers/FM2016/examples/binary_tree.dfy and binary_tree.tac
- [ ] inst ( m : Map, t : term) : instaintiate / subst the variable in the map m in t. An example is in 
  ../tacny-theory/papers/FM2016/examples/if_cntrl.dfy and if_cntrl.tac
- [x] `add_loop_inv (l : Term) / add_loop_invs(l : set<Term>)`,  
  add invariant(s) to the while loop.
  An example is in 
  ../tacny-theory/papers/FM2016/examples/if_cntrl.dfy and if_cntrl.tac
- [x] take a tactic as an argument, 
  e.g. `tactic a_tac (t : tactic)`

A todo list with low prioroty
- [ ]  `gen_lem (lem_name : string, args : variable List, pre : Term, post : Term, tac : Tactic)`
  to  generate a lemma 
  name based on the given string
- [ ]  `explore(t: Term, src : variable list, dest : variable list)`
  to get all possible results of substituting src for dest in _t_(what is the type for variables)
- [ ] `subst (t : Term, ops : map <Term, Term>)`
  to return all possible results of substituting operators in the map
- [ ] inline tactic
- [ ] if_else structure reference

**Comment by Tapanito** [comment]
Added a "get_member("MemberName");" statement to get a program member by name.  The member can then be passed to a preconditions and postconditions statements.
