### ISSUE TITLE
Refactoring TODO List

### ISSUE THREAD

**Issue by Tapanito** [ggrov/tacny#35]
- [ ] Nested tactic calls
- [ ] Find tactic application in Functions
- [ ] In Dafny resolver mark method, when tactic application is detected
- [x] Tacny variable registration
- [x] New program generation
- [ ] Merge multiple solutions into a single solution
- [ ] Generated program resolution
- [ ] Generated program verification
- [x] Parse tactic attributes
- [x] Search framework for tactics
- [x] Frames for Tacny-level variables
- [x] Call Tacny from Dafny translator
- [x] Find tactic application in Method 
- [ ] Expand TODO list
