### ISSUE TITLE
Refactorying TODO

### ISSUE THREAD

**Issue by lyhlbyl** [ggrov/tacny#43]
High Priority:
- [ ] naming attributes for tmatch
- [x] searching: real depth search and attribute
- [x] multi tac application
- [x] nested tac call
- [x] if and while control flow
- [x] partial  - at tactic call and tactic definition
- [ ] enable/disable tac eval: TacticEvaluationIsEnabled
